const { flatRoutes } = require("remix-flat-routes");

/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  future: {
    v2_routeConvention: true,
    v2_meta: true,
    unstable_postcss: true,
    unstable_tailwind: true,
  },
  ignoredRouteFiles: ["**/.*"],
  routes: async (defineRoutes) => {
    return flatRoutes(["routes", "_custom-routes"], defineRoutes);
  },
  serverDependenciesToBundle: [
    "nanoid",
    //mdx dependencies
    "axios",
    "@mdx-js/mdx",
    "@mdx-js/react",
    "acorn",
    "astring",
    "bail",
    "ccount",
    /^character-*/,
    "comma-separated-tokens",
    "decode-named-character-reference",
    "dequal",
    "diff",
    /^estree-*/,
    /^hast-*/,
    /^is-*/,
    "js-yaml",
    "kleur",
    "longest-streak",
    /^mdast-*/,
    /^micromark*/,
    "mri",
    "next-mdx-remote",
    "next-mdx-remote/serialize",
    "parse-entities",
    "periscopic",
    "property-information",
    "remark-mdx",
    "remark-parse",
    "remark-rehype",
    "sade",
    "space-separated-tokens",
    "stringify-entities",
    "style-to-object",
    "trim-lines",
    "trough",
    "unified",
    /^unist-*/,
    "uvu",
    /^vfile*/,
    "zwitch",
  ],
};
