app = "mana-typesense"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "typesense.Dockerfile"

[env]
  TYPESENSE_DATA_DIR= "/typesense-data"
  TYPESENSE_ENABLE_CORS= "true"
  TYPESENSE_API_KEY=""

[http_service]
  internal_port = 8108
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 800
    hard_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "typesense_data"
  destination = "/typesense-data"