export const showcaseSample = {
   detail_info: {
      assist_avatar: {
         skilltree_list: [
            { point_id: 1004001, level: 3 },
            { point_id: 1004002, level: 4 },
            { point_id: 1004003, level: 4 },
            { point_id: 1004004, level: 4 },
            { point_id: 1004007, level: 1 },
            { point_id: 1004101, level: 1 },
            { point_id: 1004201, level: 1 },
            { point_id: 1004202, level: 1 },
         ],
         avatar_id: 1004,
         level: 50,
         equipment: { level: 50, tid: 21015, rank: 3, promotion: 1 },
         relic_list: [
            {
               sub_affix_list: [
                  { affix_id: 4, cnt: 1, step: 2 },
                  { affix_id: 5, cnt: 1, step: 1 },
               ],
               tid: 41021,
               main_affix_id: 1,
               type: 1,
            },
            {
               sub_affix_list: [
                  { affix_id: 3, cnt: 1, step: 1 },
                  { affix_id: 5, cnt: 1, step: 2 },
                  { affix_id: 8, cnt: 1 },
                  { affix_id: 10, cnt: 2, step: 3 },
               ],
               tid: 51022,
               main_affix_id: 1,
               level: 9,
               type: 2,
            },
            {
               sub_affix_list: [
                  { affix_id: 2, cnt: 1 },
                  { affix_id: 7, cnt: 1, step: 2 },
               ],
               tid: 51023,
               main_affix_id: 7,
               type: 3,
            },
            {
               sub_affix_list: [
                  { affix_id: 11, cnt: 1 },
                  { affix_id: 12, cnt: 1 },
               ],
               tid: 31024,
               main_affix_id: 4,
               level: 6,
               type: 4,
            },
            {
               sub_affix_list: [
                  { affix_id: 1, cnt: 2, step: 4 },
                  { affix_id: 3, cnt: 1 },
                  { affix_id: 5, cnt: 1, step: 2 },
                  { affix_id: 10, cnt: 2, step: 3 },
               ],
               tid: 63055,
               main_affix_id: 3,
               level: 9,
               type: 5,
            },
            {
               sub_affix_list: [
                  { affix_id: 3, cnt: 1, step: 1 },
                  { affix_id: 6, cnt: 1 },
                  { affix_id: 8, cnt: 1, step: 1 },
                  { affix_id: 10, cnt: 2, step: 3 },
               ],
               exp: 500,
               tid: 63056,
               main_affix_id: 4,
               level: 6,
               type: 6,
            },
         ],
         rank: 3,
      },
      is_display_avatar: true,
      avatar_detail_list: [
         {
            promotion: 2,
            skilltree_list: [
               { point_id: 1102001, level: 3 },
               { point_id: 1102002, level: 4 },
               { point_id: 1102003, level: 4 },
               { point_id: 1102004, level: 4 },
               { point_id: 1102007, level: 1 },
               { point_id: 1102101, level: 1 },
               { point_id: 1102201, level: 1 },
               { point_id: 1102202, level: 1 },
               { point_id: 1102203, level: 1 },
            ],
            avatar_id: 1102,
            level: 50,
            equipment: { level: 50, tid: 23001, rank: 3, promotion: 1 },
            relic_list: [
               {
                  sub_affix_list: [
                     { affix_id: 2, cnt: 2, step: 1 },
                     { affix_id: 3, cnt: 1 },
                     { affix_id: 8, cnt: 2 },
                     { affix_id: 9, cnt: 2, step: 1 },
                  ],
                  tid: 51021,
                  main_affix_id: 1,
                  level: 12,
                  type: 1,
               },
               {
                  sub_affix_list: [
                     { affix_id: 3, cnt: 1, step: 1 },
                     { affix_id: 6, cnt: 2, step: 2 },
                     { affix_id: 7, cnt: 1, step: 1 },
                     { affix_id: 8, cnt: 2 },
                  ],
                  tid: 51022,
                  main_affix_id: 1,
                  level: 12,
                  type: 2,
               },
               {
                  sub_affix_list: [
                     { affix_id: 2, cnt: 1 },
                     { affix_id: 5, cnt: 2, step: 1 },
                     { affix_id: 6, cnt: 1, step: 2 },
                     { affix_id: 11, cnt: 3, step: 5 },
                  ],
                  tid: 55003,
                  main_affix_id: 1,
                  level: 12,
                  type: 3,
               },
               {
                  sub_affix_list: [
                     { affix_id: 4, cnt: 1, step: 1 },
                     { affix_id: 5, cnt: 2 },
                     { affix_id: 9, cnt: 2, step: 3 },
                     { affix_id: 11, cnt: 1 },
                  ],
                  tid: 51024,
                  main_affix_id: 4,
                  level: 12,
                  type: 4,
               },
               {
                  sub_affix_list: [
                     { affix_id: 2, cnt: 1, step: 1 },
                     { affix_id: 4, cnt: 2, step: 1 },
                     { affix_id: 7, cnt: 3, step: 5 },
                     { affix_id: 12, cnt: 2, step: 1 },
                  ],
                  tid: 63055,
                  main_affix_id: 9,
                  level: 15,
                  type: 5,
               },
               {
                  sub_affix_list: [
                     { affix_id: 2, cnt: 1 },
                     { affix_id: 8, cnt: 2, step: 3 },
                     { affix_id: 11, cnt: 1, step: 1 },
                     { affix_id: 12, cnt: 2, step: 1 },
                  ],
                  tid: 53066,
                  main_affix_id: 4,
                  level: 12,
                  type: 6,
               },
            ],
            rank: 3,
         },
         {
            promotion: 1,
            pos: 1,
            skilltree_list: [
               { point_id: 1211001, level: 2 },
               { point_id: 1211002, level: 4 },
               { point_id: 1211003, level: 4 },
               { point_id: 1211004, level: 4 },
               { point_id: 1211007, level: 1 },
               { point_id: 1211201, level: 1 },
            ],
            avatar_id: 1211,
            level: 50,
            equipment: { level: 50, tid: 21021, rank: 3, promotion: 3 },
            relic_list: [
               {
                  sub_affix_list: [
                     { affix_id: 2, cnt: 1, step: 2 },
                     { affix_id: 3, cnt: 1 },
                     { affix_id: 5, cnt: 1, step: 2 },
                     { affix_id: 8, cnt: 1, step: 2 },
                  ],
                  tid: 51011,
                  main_affix_id: 1,
                  level: 6,
                  type: 1,
               },
               {
                  sub_affix_list: [
                     { affix_id: 1, cnt: 1, step: 2 },
                     { affix_id: 4, cnt: 2, step: 4 },
                     { affix_id: 5, cnt: 1 },
                     { affix_id: 10, cnt: 1, step: 1 },
                  ],
                  tid: 51012,
                  main_affix_id: 1,
                  level: 6,
                  type: 2,
               },
               {
                  sub_affix_list: [
                     { affix_id: 1, cnt: 1, step: 1 },
                     { affix_id: 2, cnt: 2, step: 3 },
                     { affix_id: 7, cnt: 1 },
                     { affix_id: 11, cnt: 2, step: 1 },
                  ],
                  exp: 700,
                  tid: 55001,
                  main_affix_id: 1,
                  level: 9,
                  type: 3,
               },
               {
                  sub_affix_list: [
                     { affix_id: 1, cnt: 1, step: 2 },
                     { affix_id: 2, cnt: 1 },
                     { affix_id: 5, cnt: 1 },
                  ],
                  exp: 1000,
                  tid: 41014,
                  main_affix_id: 4,
                  level: 6,
                  type: 4,
               },
               {
                  sub_affix_list: [
                     { affix_id: 3, cnt: 1, step: 1 },
                     { affix_id: 11, cnt: 1 },
                  ],
                  tid: 53025,
                  main_affix_id: 7,
                  type: 5,
               },
               {
                  sub_affix_list: [
                     { affix_id: 2, cnt: 1, step: 1 },
                     { affix_id: 6, cnt: 1 },
                  ],
                  tid: 43026,
                  main_affix_id: 3,
                  type: 6,
               },
            ],
            rank: 3,
         },
         {
            pos: 2,
            skilltree_list: [
               { point_id: 1004001, level: 3 },
               { point_id: 1004002, level: 4 },
               { point_id: 1004003, level: 4 },
               { point_id: 1004004, level: 4 },
               { point_id: 1004007, level: 1 },
               { point_id: 1004101, level: 1 },
               { point_id: 1004201, level: 1 },
               { point_id: 1004202, level: 1 },
            ],
            avatar_id: 1004,
            level: 50,
            equipment: { level: 50, tid: 21015, rank: 3, promotion: 1 },
            relic_list: [
               {
                  sub_affix_list: [
                     { affix_id: 4, cnt: 1, step: 2 },
                     { affix_id: 5, cnt: 1, step: 1 },
                  ],
                  tid: 41021,
                  main_affix_id: 1,
                  type: 1,
               },
               {
                  sub_affix_list: [
                     { affix_id: 3, cnt: 1, step: 1 },
                     { affix_id: 5, cnt: 1, step: 2 },
                     { affix_id: 8, cnt: 1 },
                     { affix_id: 10, cnt: 2, step: 3 },
                  ],
                  tid: 51022,
                  main_affix_id: 1,
                  level: 9,
                  type: 2,
               },
               {
                  sub_affix_list: [
                     { affix_id: 2, cnt: 1 },
                     { affix_id: 7, cnt: 1, step: 2 },
                  ],
                  tid: 51023,
                  main_affix_id: 7,
                  type: 3,
               },
               {
                  sub_affix_list: [
                     { affix_id: 11, cnt: 1 },
                     { affix_id: 12, cnt: 1 },
                  ],
                  tid: 31024,
                  main_affix_id: 4,
                  level: 6,
                  type: 4,
               },
               {
                  sub_affix_list: [
                     { affix_id: 1, cnt: 2, step: 4 },
                     { affix_id: 3, cnt: 1 },
                     { affix_id: 5, cnt: 1, step: 2 },
                     { affix_id: 10, cnt: 2, step: 3 },
                  ],
                  tid: 63055,
                  main_affix_id: 3,
                  level: 9,
                  type: 5,
               },
               {
                  sub_affix_list: [
                     { affix_id: 3, cnt: 1, step: 1 },
                     { affix_id: 6, cnt: 1 },
                     { affix_id: 8, cnt: 1, step: 1 },
                     { affix_id: 10, cnt: 2, step: 3 },
                  ],
                  exp: 500,
                  tid: 63056,
                  main_affix_id: 4,
                  level: 6,
                  type: 6,
               },
            ],
            rank: 3,
         },
      ],
      uid: 600721061,
      world_level: 2,
      nickname: "F2PGod",
      gameplay_birthday: 425,
      level: 38,
      record_info: {
         challenge_info: { ENINAOFCBAP: 14 },
         PIENKNFKKFP: 6,
         JIOINJCIKFI: 26,
         avatar_count: 17,
         achievement_count: 169,
      },
      head_icon: 208002,
   },
};
